# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb813c2a428df16b29dc6b06eae68b464bcf6887a227b0e9b159d855454968c0aa145023df472902a39e3fb8189b14b918864cc54a9b4dc357da4706c2e1391

test:
  secret_key_base: bc038b016742a438082a1ccd95eaff66d7fb28609228abfee7845e5f9d055bb742a919e42bd54444bafe78a033551a72d43eebd9f79f3becaf33f2ba5c39b469

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
